// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iboivhhbblpqeytvyfvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlib2l2aGhiYmxwcWV5dHZ5ZnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTk5MTYsImV4cCI6MjA1NjMzNTkxNn0.Kt40pLcuPCMIVPDv8tX_K-omknGNapsjOfMNZJpRq_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);